project:
  type: website
  output-dir: docs
  render:
    - general_eda.qmd

execute:
  freeze: auto
  
html:
  comments:
    utterances:
       repo: zadchin/alpha_test

format:
  revealjs:
    multiplex: true
    preview-links: auto
    logo: images/quarto.png
    css: styles.css
    format:
    includes:
      in-header: _utterances.html