project:
  type: website
  output-dir: docs
  render:
    - general_eda.qmd

execute:
  freeze: auto
  
comments:
  giscus:
    repo: zadchin/alpha_test

format:
  revealjs:
    multiplex: true
    preview-links: auto
    logo: images/quarto.png
    css: styles.css
  html:
    embed-resources: true