project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - general_eda.qmd

execute:
  freeze: auto

format:
  revealjs:
    multiplex: true
    preview-links: auto
    logo: images/quarto.png
    css: styles.css
    includes:
      in-header: _utterances.html